[package]
name = "han-non-e-admin"
version = "0.1.0"
description = "문무니 관리자"
authors = ["han-non-e"]
edition = "2021"

[lib]
name = "han_non_e_admin_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
